### ISSUE TITLE
sync gitlab repo to github

### ISSUE THREAD

**Issue by stardustman** [Enteee/git-sync-mirror#16]
can I use it sync gitlab repo to github repo?

**Comment by Enteee** [comment]
yes that should work.

**Comment by tlevin1** [comment]
Can you use docker compose with this repo? I am having trouble setting it up properly @Enteee

**Comment by Enteee** [comment]
@tlevin1 yes you can use this docker image in a docker compose configuration.

please open a new issue if think something should be changed in this image.
